spring:
  security:
    user:
      name: admin
      password: ikea#2019
      roles:
        - ACTUATOR_ADMIN
        - UPLOAD_ADMIN
        - REFRESH_ADMIN
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  messages:
    basename: messages.identity,messages.account,messages.common,messages.product,messages.checkout,messages.rix,messages.iows,messages.idaas
    encoding: UTF-8

aliyun:
  oss:
    base-url: https://res-dev.app.ikea.cn
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI4FjYwjB1S65q9baXaesc
    access-key-secret: RJPa5W5LsaHHHVQVn9tEWIIoD3YKww
    bucket-name: ikea-app-dev

ikea:
  retail-unit: cn
  language: zh
  security:
    rsaPubKey: '{"kty":"RSA","kid":"5284653461972686632","alg":"RS256","n":"gePx5XoDT-fLB8EmJeSkS024DRb7PqVAKR7ah1UGt_w4kNUVht7fZrmiRB5QxWS_aMkzMCHMDgZigF1b8KC576DDQG_aUOontd8G3SbUtvNF-1yIuI2Q1plyxAyY0z02p0CXlgN9-GivpXOzeN__vOQQBQOZq1QSPx8iYAddAZjdSzjHWBTGpaPZECEvMo0N4oK2Eo_Gfykw0vZVVKruqUNkOfQgxcEO90jz-VrfEhpwoGfEKG1j_dYBiQKFtGUQcjlGxBMWecTWN8ujLxCQN8NgWrNauePxbrHIh9oe_oc5HM8xqMlut3ceq5ggIG_u5B_Mqt8Qbtww_3yhuyQ0YQ","e":"AQAB"}'
    #rsaPubKey: '{"kty":"RSA","kid":"732846008430691728","alg":"RS256", "n": "o1EgWG9g-LsVZhsCzhr6HidRbdGEytZ7UQr7MHWgS0uqGgUe-jqMeokzyZZHPSqS0J5XPWZMC0jvDM5Ze4dBce7oE8j0OGbE3b0Vcs2VYC0O8_2oHngHyqhlz59RHFGTf4n4Hyp_RG4n6woBgTcTQHplq6YyaYCrVc7KMqUz18mLZB5WcRVaE9pHUcLnWDwzuIJEewctkocd0bo70cNF77EwhQ_SbkLzLQ3JuvAXd4YITfarlOL1E5QgaVdOnr1Ly4WJiebdr5BzFCZTZGosCjDzqqrNkEFy1SoGDSv41H8yS_APX8iYrGwL1Ozgvbntj0GDdok--u7Fi3D4CF70fw", "e":"AQAB"}'
  iows:
    imageHost: https://www.ikea.cn
    url: https://iows.ikea.cn
    consumer: IKEAAPPA
    contract: 40662
  iows-auth:
    url: https://iows.ikea.cn
    consumer: IKEAAPPA
    contract: 40662
  ali:
    url: https://prod.rec.ikea.cn
  rix:
    url: https://api.ingka.ppe.ikeadt.com
    x-client-id: ac5426e9-2039-4b79-b9ad-00a413a928d2
  esales:
    url: https://w046ff4d5.api.esales.apptus.cloud
    market: CNZH
    lastWindow: 9999
  checkout:
    url: https://checkout-service.ocp.ingka.ikea.cn
    # url: https://checkout-service-dev.ocp.ingka.ikea.cn
  csh:
    #    url: http://csh-security.mez100.com.cn/
    url: https://csh.ikea.cn
  mfs:
    url: https://api.ingka.ikea.cn
  internal-service:
    idaas:
      baseUrl: https://jdmmkxwmyj.api.aliyunidaas.com
      enterpriseId: idaas-cn-mp91bhy9d01
      enterpriseAuthId: idaas-cn-mp91bhy9d01lazy_loading
      appKey: 34c24b0f713dd58a9653a85399e2fccbFrBQoD5trJY
      #baseUrl: https://ikeatest.idp4.idsmanager.com
      #enterpriseId: ikeatest
      #enterpriseAuthId: ikeatestwechat
      #appKey: 498cf748409370cf161422d4c630c3aeFqxD8lMnw2S

server:
  compression:
    enabled: true

swagger:
  enable: true

management:
  server:
    port: 8009
  endpoints:
    web:
      exposure:
        include: health,refresh
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: when_authorized
      roles: ACTUATOR_ADMIN

logging:
  config: classpath:logback/logback-console.xml